-- Some of this version was generated by pgAdmin and the rest was written by Romina Lodolo

BEGIN;


CREATE TABLE IF NOT EXISTS public.Department
(
    depart_id bigint NOT NULL DEFAULT nextval('"Department_depart_id_seq"'::regclass),
    depart_name character varying(50) COLLATE pg_catalog."default",
    depart_city character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Department_pkey" PRIMARY KEY (depart_id)
);

CREATE TABLE IF NOT EXISTS public.Employees
(
    emp_id bigint NOT NULL DEFAULT nextval('"Employees_emp_id_seq"'::regclass),
    first_name character varying(50) COLLATE pg_catalog."default",
    surname character varying(50) COLLATE pg_catalog."default",
    gender character varying(25) COLLATE pg_catalog."default",
    address character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    depart_id character varying(25) COLLATE pg_catalog."default",
    role_id character varying(20) COLLATE pg_catalog."default",
    salary_id money,
    overtime_id integer,
    CONSTRAINT employee_id PRIMARY KEY (emp_id)
);

CREATE TABLE IF NOT EXISTS public.OvertimeHours
(
    overtime_id bigint NOT NULL DEFAULT nextval('"OvertimeHours_overtime_id_seq"'::regclass),
    overtime_hours integer,
    CONSTRAINT "OvertimeHours_pkey" PRIMARY KEY (overtime_id)
);

CREATE TABLE IF NOT EXISTS public.Roles
(
    role_id bigint NOT NULL DEFAULT nextval('"Roles_role_id_seq"'::regclass),
    role character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT "Roles_pkey" PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    salaries_id bigint NOT NULL DEFAULT nextval('salaries_salaries_id_seq'::regclass),
    salary_pa money,
    CONSTRAINT salaries_pkey PRIMARY KEY (salaries_id)
);

INSERT INTO "OvertimeHours" (overtime_id, overtime_hours)
VALUES 
  (1,5),
  (2,7),
  (3,1),
  (4,8),
  (5,3),
  (6,5),
  (7,7),
  (8,4),
  (9,2),
  (10,3);

INSERT INTO `Roles` (`role_id`, `role`)
VALUES 
  (1,"HR"),
  (2,"PR"),
  (3,"Admin"),
  (4,"Security"),
  (5,"IT"),
  (6,"Design"),
  (7,"CEO"),
  (8,"COO"),
  (9,"Accounting"),
  (10,"Marketing");

INSERT INTO `Salary` (`salaries_id`, `salary_pa`)
VALUES 
  (1,5000),
  (2,12000),
  (3,4000),
  (4,2000),
  (5,30200),
  (6,21000),
  (7,50000),
  (8,43000),
  (9,32000),
  (10,18000);


INSERT INTO `Department` (`depart_id`, `depart_name`, `depart_city`)
VALUES 
  (1,"Human Resource", "Joburg"),
  (2,"Public Relations", "Joburg"),
  (3,"Administrater", "Joburg"),
  (4,"Security", "Joburg"),
  (5,"Software and Tech", "Joburg"),
  (6,"Marketing", "Joburg"),
  (7,"Leaders", "Pretoria"),
  (8,"Leaders", "Joburg"),
  (9,"Accounting", "Joburg"),
  (10,"Marketing", "Pretoria");


INSERT INTO Employees (first_name,surname, gender, address,email, depart_id, role_id, salary_id, overtime_id)
VALUES
  ("Tasha","Kline", "Female","1451 A St.","sit.amet.consectetuer@yahoo.ca"),
  ("Jamal","Watts", "Female", "556-9451 In St.","in.molestie.tortor@protonmail.com"),
  ("Shana","Ramos", "Female", "177-9008 Curabitur St.","sed.pede@google.org"),
  ("Rooney","Hicks", "Male", "6615 Massa. St.","luctus.vulputate.nisi@aol.couk"),
  ("Perry","Pace", "Male", "P.O. Box 171, 7471 Phasellus Av.","pede.nonummy.ut@yahoo.net"),
  ("Cecilia","Hubbard", "Female", "206-9948 Pellentesque Avenue","donec@aol.edu"),
  ("Jerome","Flynn", "Male", "Ap #557-1255 Tincidunt Ave","cursus.integer@yahoo.ca"),
  ("Minerva","Spencer", "Male", "Ap #996-3155 Eu St.","montes.nascetur@protonmail.net"),
  ("Channing","Robinson", "Male", "P.O. Box 229, 3397 Quam Ave","diam@icloud.net"),
  ("Wing","Calhoun", "Female", "Ap #640-3599 Lorem St.","ipsum@yahoo.net");


ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT overtime_id FOREIGN KEY (overtime_id)
    REFERENCES public."OvertimeHours" (overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT role_id FOREIGN KEY (role_id)
    REFERENCES public."Roles" (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT depart_id FOREIGN KEY (depart_id)
    REFERENCES public."Department" (depart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT salary_id FOREIGN KEY (salary_id)
    REFERENCES public.salaries (salaries_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;




SELECT emp.first_name, emp.surname, emp.gender, emp.address, emp.email,
depart.depart_name, depart.depart_city, 
role."Roles",
sal.salary_pa,
ot."OvertimeHours"
FROM Employees AS emp LEFT JOIN Department AS dept
ON emp.depart_id = depart.depart_id
LEFT JOIN Role
ON emp.role_id = role.role_id
LEFT JOIN Salary AS sal
ON emp.salaries_id = sal.salaries_id
LEFT JOIN Overtime AS ot
ON emp.overtime_id = ot.overtime_id

END;