-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Department"
(
    depart_id bigint NOT NULL DEFAULT nextval('"Department_depart_id_seq"'::regclass),
    depart_name character varying(50) COLLATE pg_catalog."default",
    depart_city character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Department_pkey" PRIMARY KEY (depart_id)
);

CREATE TABLE IF NOT EXISTS public."Employees"
(
    emp_id bigint NOT NULL DEFAULT nextval('"Employees_emp_id_seq"'::regclass),
    first_name character varying(50) COLLATE pg_catalog."default",
    surname character varying(50) COLLATE pg_catalog."default",
    gender character varying(25) COLLATE pg_catalog."default",
    address character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    depart_id character varying(25) COLLATE pg_catalog."default",
    role_id character varying(20) COLLATE pg_catalog."default",
    salary_id money,
    overtime_id integer,
    CONSTRAINT employee_id PRIMARY KEY (emp_id)
);

CREATE TABLE IF NOT EXISTS public."Overtime Hours"
(
    overtime_id bigint NOT NULL DEFAULT nextval('"Overtime Hours_overtime_id_seq"'::regclass),
    overtime_hours integer,
    CONSTRAINT "Overtime Hours_pkey" PRIMARY KEY (overtime_id)
);

CREATE TABLE IF NOT EXISTS public."Roles"
(
    role_id bigint NOT NULL DEFAULT nextval('"Roles_role_id_seq"'::regclass),
    role character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT "Roles_pkey" PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    salaries_id bigint NOT NULL DEFAULT nextval('salaries_salaries_id_seq'::regclass),
    salary_pa money,
    CONSTRAINT salaries_pkey PRIMARY KEY (salaries_id)
);

INSERT INTO `Employees` (`first_name`,`surname`, `gender`, `address`,`email`)
VALUES
  ("Tasha","Kline", "Female","1451 A St.","sit.amet.consectetuer@yahoo.ca"),
  ("Jamal","Watts", "Female", "556-9451 In St.","in.molestie.tortor@protonmail.com"),
  ("Shana","Ramos", "Female", "177-9008 Curabitur St.","sed.pede@google.org"),
  ("Rooney","Hicks", "Male", "6615 Massa. St.","luctus.vulputate.nisi@aol.couk"),
  ("Perry","Pace", "Male", "P.O. Box 171, 7471 Phasellus Av.","pede.nonummy.ut@yahoo.net"),
  ("Cecilia","Hubbard", "Female", "206-9948 Pellentesque Avenue","donec@aol.edu"),
  ("Jerome","Flynn", "Male", "Ap #557-1255 Tincidunt Ave","cursus.integer@yahoo.ca"),
  ("Minerva","Spencer", "Male", "Ap #996-3155 Eu St.","montes.nascetur@protonmail.net"),
  ("Channing","Robinson", "Male", "P.O. Box 229, 3397 Quam Ave","diam@icloud.net"),
  ("Wing","Calhoun", "Female", "Ap #640-3599 Lorem St.","ipsum@yahoo.net");

ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT overtime_id FOREIGN KEY (overtime_id)
    REFERENCES public."Overtime Hours" (overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT role_id FOREIGN KEY (role_id)
    REFERENCES public."Roles" (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT depart_id FOREIGN KEY (depart_id)
    REFERENCES public."Department" (depart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees"
    ADD CONSTRAINT salary_id FOREIGN KEY (salary_id)
    REFERENCES public.salaries (salaries_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;




SELECT emp.first_name, emp.surname, emp.gender, emp.address, emp.email,
dept.depart_name, dept.depart_city, 
role.role,
sal.salary_pa,
ot.overtime_hours
FROM Employees AS emp LEFT JOIN Department AS dept
ON emp.depart_id = dept.depart_id
LEFT JOIN Role
ON emp.role_id = role.role_id
LEFT JOIN Salary AS sal
ON emp.salary_id = sal.salary_id
LEFT JOIN Overtime AS ot
ON emp.overtime_id = ot.overtime_id

END;