-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.



CREATE TABLE IF NOT EXISTS EmployeeDB.Employees 
(
    first_name character varying(50),
    surname character varying(50),
    gender character varying(25),
    address character varying(50),
    email character varying(50),
    depart_id integer,
    role_id integer,
    salary_id integer,
    overtime_id integer,
    emp_id bigserial NOT NULL GENERATED ALWAYS AS IDENTITY,
    CONSTRAINT emp_key PRIMARY KEY (emp_id)
);

CREATE TABLE IF NOT EXISTS public."Department"
(
    depart_id bigserial,
    depart_name character varying(50),
    depart_city character varying(50)
);

CREATE TABLE IF NOT EXISTS public."Roles"
(
    role_id bigserial,
    role character varying(50)
);

CREATE TABLE IF NOT EXISTS public."Salaries"
(
    salary_id bigserial,
    salary_pa money
);

CREATE TABLE IF NOT EXISTS public."Overtime Hours"
(
    overtime_id bigserial,
    overtime_hours integer
);

ALTER TABLE IF EXISTS public."Employees "
    ADD CONSTRAINT depart_id FOREIGN KEY (depart_id, role_id, salary_id, overtime_id)
    REFERENCES public."Department" (depart_id, role_id, salary_id, overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees "
    ADD FOREIGN KEY (depart_id)
    REFERENCES public."Department" (depart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees "
    ADD FOREIGN KEY (role_id)
    REFERENCES public."Roles" (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees "
    ADD FOREIGN KEY (salary_id)
    REFERENCES public."Salaries" (salary_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employees "
    ADD FOREIGN KEY (overtime_id)
    REFERENCES public."Overtime Hours" (overtime_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Department"
    ADD CONSTRAINT depart_key FOREIGN KEY (depart_id, depart_name)
    REFERENCES public."Department" (depart_id, depart_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Roles"
    ADD CONSTRAINT role_key FOREIGN KEY (role_id, role)
    REFERENCES public."Roles" (role_id, role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Salaries"
    ADD CONSTRAINT salary_key FOREIGN KEY (salary_id, salary_pa)
    REFERENCES public."Salaries" (salary_id, salary_pa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Salaries"
    ADD FOREIGN KEY (salary_id)
    REFERENCES public."Salaries" (salary_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Overtime Hours"
    ADD CONSTRAINT overtime_key FOREIGN KEY (overtime_id, overtime_hours)
    REFERENCES public."Overtime Hours" (overtime_id, overtime_hours) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
